// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package generatedsql

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID         int64
	Value      string
	Author     string
	QuestionID pgtype.Int8
}

type Poll struct {
	ID   uuid.UUID
	Name string
}

type Question struct {
	ID     int64
	Value  string
	PollID uuid.UUID
	Votes  pgtype.Int4
}
