// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package generatedsql

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Poll struct {
	ID   uuid.UUID
	Name string
}

type Question struct {
	ID     pgtype.Int8
	Value  string
	PollID uuid.UUID
	Votes  pgtype.Int4
}
