// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package generatedsql

import (
	"context"
)

const createPoll = `-- name: CreatePoll :one
INSERT INTO
    polls (name)
VALUES
    ($1) RETURNING id, name
`

func (q *Queries) CreatePoll(ctx context.Context, name string) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll, name)
	var i Poll
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
