-- +goose Up
-- +goose StatementBegin
CREATE TABLE questions(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    value text NOT NULL,
    poll_id uuid REFERENCES polls (id),
    votes integer DEFAULT 0
);

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DROP TABLE questions;

-- +goose StatementEnd