-- +goose Up
-- +goose StatementBegin
CREATE TABLE comments(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value text NOT null,
    author varchar(16) NOT null,
    question_id bigint REFERENCES questions(id) ON DELETE CASCADE
);

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DROP TABLE comments
-- +goose StatementEnd